steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: [
            'build',
            '-t',
            'gcr.io/rahul-lab/flaskapp:${SHORT_SHA}',
            '.'
          ]

  # Docker push to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'gcr.io/rahul-lab/flaskapp:${SHORT_SHA}']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
            'run',
            'deploy',
            'flaskapp',
            '--image',
            'gcr.io/rahul-lab/flaskapp:${SHORT_SHA}',
            '--region',
            'northamerica-northeast2 ',
            '--platform',
            'managed',
            '--allow-unauthenticated', # Optional, depending on your authentication requirements
            '--api-endpoint-override=https://northamerica-northeast2-run.googleapis.com/'
          ]
options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
