steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: [
            'build',
            '-t',
            'gcr.io/rahul-lab/flaskapp:${SHORT_SHA}',
            '-t',
            'gcr.io/rahul-lab/flaskapp:latest',
            '--cache-from',
            'gcr.io/rahul-lab/flaskapp:latest',
            '.'
          ]
 
  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'gcr.io/rahul-lab/flaskapp:${SHORT_SHA}']
 
# Store images in Google Artifact Registry 
images:
  - gcr.io/rahul-lab/flaskapp:${SHORT_SHA}
  - gcr.io/rahul-lab/flaskapp:latest
 
options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
